name: Build

on:
  workflow_dispatch:
  push:
    # paths: '**.ts'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: build
      #   env:
      #    github_token: 
        run: |
          npm install
          tsc
          cp package.json org_out/
          cp manifest.json org_out/
          mkdir out
          cd org_out && 7z a -tzip -r ../out/Organization.llplugin .
          7z a -tzip -r ../out/Organization.zip .
        # git config user.name "xianyubb"
        # git config user.email "2149656630@qq.com"
        # git add -f .
        # git commit -a -m "now"
        # git remote add target https://github.com/xianyubb/org_out
        # git push target HEAD:refs/heads/main
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Organization
          path: org_out/
