name: Release

on:
  workflow_dispatch:
  push:
    # tags:
    #   - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          cp package.json Organization/
          cp manifest.json Organization/
          cp tooth.json Organization/
          mkdir out
          cd Organization && 7z a -tzip -r ../out/Organization.llplugin .
          7z a -tzip -r ../out/Organization.zip .
          git config user.email "2149656630@qq.com"
          git config user.name "xianyubb"
          git add -f .
          git commit -m "new"
      - name: Push to anothor repository
        uses: ad-m/github-push-action@master
        with:
          env: ${{ secrets.ACCESS_TOKEN }}
          github_token: ${{ secrets.xianyubb }}
          repository: xianyubb/org_out
          force: true
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Organization
          path: Organization/
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: Organization
      #     files: ./out/*
          
